set(PKG_NAME gemtest_pi)
set(PKG_VERSION 0.0.1.0)
set(PKG_PRERELEASE "")
set(DISPLAY_NAME [GEM Test])
set(PLUGIN_API_NAME [GEM Test])
set(PKG_SUMMARY "GEM OpenCPN vector object callback test")
set(PKG_DESCRIPTION [=[Minimal diagnostic plugin to test WANTS_VECTOR_CHART_OBJECT_INFO with oeSENC charts.]=])
set(PKG_AUTHOR "GEM Marine")
set(PKG_IS_OPEN_SOURCE "yes")
set(CPACK_PACKAGE_HOMEPAGE_URL https://github.com/ffolkes-gem/gem-opencpn-bridge)
set(PKG_INFO_URL https://github.com/ffolkes-gem/gem-opencpn-bridge)

set(SRC src/gemtest_pi.cpp)
set(HEADERS include/gemtest_pi.h)
set(PKG_API_LIB api-19)
add_compile_definitions(_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR)
macro(late_init)
endmacro()
macro(add_plugin_libraries)
endmacro()
